# Generated by Django 5.0.1 on 2024-01-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.CharField()),
                ('release_date', models.DateField()),
                ('lte_exists', models.BooleanField()),
                ('slug', models.CharField()),
            ],
        ),
    ]
